ratings/urls.py
from django.urls import path
from ratings import views

app_name="ratings"

urlpatterns=[
path('',views.main_view,name="main"),
path('rate-image',views.rate_image,name="rate_image")
]

src/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("ratings.urls"))
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

ratings/models.py
from django.db import models
from django.core.validators import MaxValueValidator,MinValueValidator

class Rating(models.Model):
    image=models.ImageField(upload_to="image/")
    score=models.IntegerField(default=0,
    validators=[
    MaxValueValidator(5),
    MinValueValidator(0)
    ]
    )

    def __str__(self):
        return str(self.pk)

ratings/forms.py
from django import forms
from django.forms import ModelForm

ratings/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse
from ratings.models import Rating


def main_view(request):
    obj=Rating.objects.all().order_by("?").first()
    context={
    "object":obj
    }
    return render(request,"ratings/main.html",context)
def rate_image(request):
    if request.method=="POST":
        el_id=request.POST.get('el_id')
        val=request.POST.get('val')
        obj=Rating.objects.get(id=el_id)
        obj.score=val
        obj.save()
        return JsonResponse({'success':'true','score':val},safe=False)
    return JsonResponse({'success':'false'})

templates/ratings/base.html
{%load static%}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- =================== -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script> -->
    <!-- ==================== -->
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
<link rel="stylesheet" href="{%static 'css/style.css'%}">
<script scr="{%static 'js/main.js'%}"></script>
    <title>{%block title%}{%endblock%}</title>
  </head>
  <body>
    <div class="container mt-3">
  {%block content%}
  {%endblock%}
</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  </body>
</html>

templates/ratings/main.html
{%extends "ratings/base.html"%}
{%load static%}
<link rel="stylesheet" href="{%static 'css/style.css'%}">
<script scr="{%static 'js/main.js'%}"></script>
{%block title%}
Rate Now
{%endblock%}
{%block content%}
<style type="text/css">
.checked{
  color:orange;
}
.my-btn{
  background-color:inherit !important;
  border:0 !important;
}
</style>
<!--  -->
<div class="row">
<div class="col text-center">
<img src="{{object.image.url}}" class="rounded" width="100%" alt="#">
<br>

<a href="{%url 'ratings:main'%}"><button class="btn btn-outline-primary mt-3">Next</button></a>
</div>


<div class="col text-center">
  <form class="rate-form" action="" method="POST" id="{{object.id}}">
    {%csrf_token%}
<button type="submit" class="fa fa-star fa-3x my-btn" id="first"></button>
<button type="submit" class="fa fa-star fa-3x my-btn" id="second"></button>
<button type="submit" class="fa fa-star fa-3x my-btn" id="third"></button>
<button type="submit" class="fa fa-star fa-3x my-btn" id="fourth"></button>
<button type="submit" class="fa fa-star fa-3x my-btn" id="fifth"></button>
</form>
<br>
<div id="confirm-box"></div>
</div>

</div>
<!--  -->
<legend>No images to rate</legend>
<!--  -->



<script type="text/javascript">
// Get all the stars
const one=document.getElementById('first')
const two=document.getElementById('second')
const three=document.getElementById('third')
const four=document.getElementById('fourth')
const five=document.getElementById('fifth')


const form=document.querySelector('.rate-form')
const confirmBox=document.getElementById('confirm-box')

const csrf=document.getElementsByName('csrfmiddlewaretoken')

const handleStarSelect=(size)=>{
  const children=form.children
for (let i =0; i<children.length;i++){
  if(i<=size){
    children[i].classList.add('checked')
  }
  else{
    children[i].classList.remove('checked')
  }
}
}

const handleSelect=(selection)=>{
  switch(selection){
    case 'first':{
      // one.classList.add('checked')
      // two.classList.remove('checked')
      // three.classList.remove('checked')
      // four.classList.remove('checked')
      // five.classList.remove('checked')
      handleStarSelect(1)
      return
    }

    case 'second':{
      handleStarSelect(2)
      return
    }

    case 'third':{
      handleStarSelect(3)
      return
    }

    case 'fourth':{
      handleStarSelect(4)
      return
    }

    case 'fifth':{
      handleStarSelect(5)
      return
    }
  }
}

const getNumericValue=(stringValue)=>{
  let numericValue;
  if (stringValue==="first"){
    numericValue=1
  }
  else if (stringValue==="second"){
    numericValue=2
  }
  else if (stringValue==='third'){
    numericValue=3
  }
  else if (stringValue==="fourth"){
    numericValue=4
  }
  else if (stringValue==="fifth"){
    numericValue=5
  }
  else {
    numericValue=0
  }
  return numericValue
}

if (one){
  const arr=[one,two,three,four,five]
  arr.forEach(item=> item.addEventListener('mouseover',(event)=>{
    handleSelect(event.target.id)
  }))

  arr.forEach(item=>item.addEventListener('click',(event)=>{
    const val= event.target.id
    console.log(val)

    let isSubmit=false

    form.addEventListener("submit",e=>{
      e.preventDefault()
      if (isSubmit){
        return
      }

      const id=e.target.id
      console.log(id)
      const val_num=getNumericValue(val)

      $.ajax({
        type:"POST",
        url:"{%url 'ratings:rate_image'%}",
        data:{
          'csrfmiddlewaretoken':csrf[0].value,
          'el_id':id,
          'val':val_num,
        },
        success: function(response){
          console.log(response)
          confirmBox.innerHTML='<h1>Successfully Rated with '+response.score+'</h1>'
        },
        error: function(error){
          console.log(error)
          confirmBox.innerHTML="<h1>Uuups... Something went wrong</h1>"
        }
      })
    })
  }))
}



</script>
{%endblock%}